Creating a logger pattern
Airtap-dev/macos pull request #13
Opened 2021-07-17 19:35 UTC by andreev-io

2021-07-17 19:43 UTC, alxdrlitreev requested changes
Good, but need some minor adjustments

2021-07-17 19:43 UTC, alxdrlitreev commented on Airtap/Providers/LogProvider.swift
> +enum logLevel: Equatable {
`enums` names should start with uppercase letter in Swift

2021-07-17 19:43 UTC, alxdrlitreev commented on Airtap/Providers/LogProvider.swift
> +    private(set) var log: [LogEntry] = []
There is no need for `log` to be visible outside of the class. Please make it strictly private and remove it from protocol.

2021-07-18 20:55 UTC, andreev-io commented on Airtap/Providers/LogProvider.swift
> +enum logLevel: Equatable {
Fixed

2021-07-18 20:55 UTC, andreev-io commented on Airtap/Providers/LogProvider.swift
> +    private(set) var log: [LogEntry] = []
Fixed

2021-07-18 20:56 UTC, andreev-io commented
I didn't add logs _everywhere_, only to some places. I suggest we add later them as we find necessary.

2021-07-26 20:37 UTC, andreev-io commented
Updated the PR, leaving it to you to integrate with Sentry @alxdrlitreev

2021-07-29 13:01 UTC, alxdrlitreev requested changes

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Network/API/APIService.swift
> +        self.logProvider.add(LogLevel.debug, String(format: "creating a new account"))
Don't get why we need formatter here. Simply replace with:
`self.logProvider.add(.debug, "creating a new account")`

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Network/API/APIService.swift
> +        self.logProvider.add(LogLevel.debug, String(format: "creating a new account"))
`LogLevel` is also redundant. Just `.debug`.

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Network/WS/WSService.swift
> +        self.logProvider.add(LogLevel.debug, String(format: "account %d sending an offer to account %d", self.authProvider.accountId!, accountId))
Replace `self.authProvider.accountId!` with `self.authProvider.accountId ?? "UNKNOWN"`. And `LogLevel.debug` with just `.debug`.

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Network/WS/WSService.swift
> +        self.logProvider.add(LogLevel.debug, String(format: "account %d sending an answer to account %d", self.authProvider.accountId!, accountId))
Replace `self.authProvider.accountId!` with `self.authProvider.accountId ?? "UNKNOWN"`. And `LogLevel.debug` with just `.debug`.

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Network/WS/WSService.swift
> +        self.logProvider.add(LogLevel.debug, String(format: "account %d sending a candidate to account %d", self.authProvider.accountId!, accountId))
Replace `self.authProvider.accountId!` with `self.authProvider.accountId ?? "UNKNOWN"`. And `LogLevel.debug` with just `.debug`.

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Network/WS/WSService.swift
> +        self.logProvider.add(LogLevel.debug, String(format: "account %d sending info to account %d", self.authProvider.accountId!, accountId))
Replace `self.authProvider.accountId!` with `self.authProvider.accountId ?? "UNKNOWN"`. And `LogLevel.debug` with just `.debug`.

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Network/WS/WSService.swift
> +        self.logProvider.add(LogLevel.debug, String(format: "account %d sending %d ack", self.authProvider.accountId!, nonce))
Replace `self.authProvider.accountId!` with `self.authProvider.accountId ?? "UNKNOWN"`. And `LogLevel.debug` with just `.debug`.

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Network/WS/WSService.swift
> +            self.logProvider.add(LogLevel.debug, String(format: "account %d received an ack", self.authProvider.accountId!))
Replace `self.authProvider.accountId!` with `self.authProvider.accountId ?? "UNKNOWN"`. And `LogLevel.debug` with just `.debug`.

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Network/WS/WSService.swift
> +            self.logProvider.add(LogLevel.debug, String(format: "account %d received an offer from %d", self.authProvider.accountId!, accountId))
Replace `self.authProvider.accountId!` with `self.authProvider.accountId ?? "UNKNOWN"`. And `LogLevel.debug` with just `.debug`.

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Network/WS/WSService.swift
> +            self.logProvider.add(LogLevel.debug, String(format: "account %d received an answer from %d", self.authProvider.accountId!, accountId))
Replace `self.authProvider.accountId!` with `self.authProvider.accountId ?? "UNKNOWN"`. And `LogLevel.debug` with just `.debug`.

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Network/WS/WSService.swift
> +            self.logProvider.add(LogLevel.debug, String(format: "account %d received a candidate from %d", self.authProvider.accountId!, accountId))
Replace `self.authProvider.accountId!` with `self.authProvider.accountId ?? "UNKNOWN"`. And `LogLevel.debug` with just `.debug`.

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Network/WS/WSService.swift
> +            self.logProvider.add(LogLevel.debug, String(format: "account %d received info from %d", self.authProvider.accountId!, accountId))
Replace `self.authProvider.accountId!` with `self.authProvider.accountId ?? "UNKNOWN"`. And `LogLevel.debug` with just `.debug`.

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Network/WS/WSService.swift
> +            self.logProvider.add(LogLevel.debug, String(format: "account %d received peers \(message.payload as Optional)", self.authProvider.accountId!))
Replace `self.authProvider.accountId!` with `self.authProvider.accountId ?? "UNKNOWN"`. And `LogLevel.debug` with just `.debug`.

Also, `message.payload as Optional` is unacceptable.

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Network/WS/WSService.swift
> +            logProvider.add(LogLevel.debug, "\(payload)")
Replace `LogLevel.debug` with just  `.debug`.

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Providers/AuthProvider.swift
> +        self.logProvider.add(LogLevel.debug, String(format: "account %d signing in", accountId))
Same here.

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Providers/AuthProvider.swift
> +        self.logProvider.add(LogLevel.debug, String(format: "account %d signing out", self.accountId!))
No unwraps, just debug

2021-07-29 13:01 UTC, alxdrlitreev commented on Airtap/Providers/PersistenceProvider.swift
> +        self.logProvider.add(LogLevel.debug, String(format: "account %d inserted peer %d into persistence", self.authProvider.accountId!, id))
Same and everywhere else.

2021-07-29 21:03 UTC, andreev-io commented
Fixed & addressed all

2021-07-30 05:48 UTC, alxdrlitreev commented
Conflicts @andreev-io :(

2021-07-30 20:31 UTC, andreev-io commented
Fixed. Can merge now.

2021-07-30 20:59 UTC, merged